import QtQuick
import QtTest
import Quickshell

// Exercise the production QML Process/JSONL adapter against the compiled Go
// backend's fictional, in-memory dataset. No API, keyring, files or microphone.
// Run offscreen on a private bus with BEEPER_TEST_BACKEND pointing to the binary.
ShellRoot {
  id: fixture
  property var beeperData: null

  function startupFailure(message) {
    console.error(message);
    Qt.callLater(() => Qt.exit(1));
  }

  Component.onCompleted: {
    if (Quickshell.env("QT_QPA_PLATFORM") !== "offscreen") {
      startupFailure("MessengerProtocol requires QT_QPA_PLATFORM=offscreen.");
      return;
    }
    const binary = Quickshell.env("BEEPER_TEST_BACKEND");
    if (!binary || binary[0] !== "/") {
      startupFailure("BEEPER_TEST_BACKEND must name an absolute compiled backend path.");
      return;
    }
    const component = Qt.createComponent("file://" + Quickshell.shellDir + "/../features/messenger/BeeperData.qml");
    if (component.status !== Component.Ready) {
      startupFailure(component.errorString());
      return;
    }
    beeperData = component.createObject(fixture, {
      demo: false,
      command: [binary, "--stdio", "--demo"]
    });
    if (!beeperData) startupFailure("Could not create the real BeeperData adapter.");
  }

  TestResult { id: results }
  TestCase {
    name: "MessengerProtocol"
    when: fixture.beeperData !== null

    function initTestCase() {
      verify(!beeperData.demo, "The QML adapter must use its production Process transport.");
      tryVerify(() => beeperData.connected && beeperData.accounts.length > 0 && beeperData.chats.length > 0, 5000);
      compare(beeperData.state, "demo", "The connected Go process must explicitly be in demo mode.");
      verify(beeperData.chats[0].id.startsWith("demo-"), "Rows must come from Go, not the QML fixture.");
      compare(Object.keys(beeperData.demoMessages).length, 0);
      beeperData.selectChat(beeperData.chats[0].id);
      tryVerify(() => !beeperData.loadingMessages && beeperData.messages.length > 0, 5000);
    }

    function cleanupTestCase() {
      console.log("MessengerProtocol: " + results.passCount + " passed, " + results.failCount + " failed");
      Qt.callLater(() => Qt.exit(results.failCount ? 1 : 0));
    }

    function cleanup() {
      if (results.failed) console.error("FAILED", qtest_results.functionName);
    }

    function test_draft_roundtrip_and_exactly_one_send_through_go() {
      const chatID = beeperData.currentChatID;
      const originalCount = beeperData.messages.length;
      const text = "Été à Paris, cœur et café 🌿\nDeuxième ligne : « salut » et \\\nTroisième ligne 💙";
      let saved = false, saveResult = null, saveError = null;
      beeperData.draftText = text;
      beeperData.flushDraft((result, error) => {
        saveResult = result; saveError = error; saved = true;
      });
      tryVerify(() => saved, 3000);
      compare(saveError, null);
      compare(saveResult.text, text);

      let loaded = false, draft = null, draftError = null;
      beeperData.request("getDraft", {chatID: chatID}, (result, error) => {
        draft = result; draftError = error; loaded = true;
      });
      tryVerify(() => loaded, 3000);
      compare(draftError, null);
      compare(draft.text, text, "Unicode and embedded newlines must survive both JSONL directions.");

      beeperData.sendMessage();
      tryCompare(beeperData, "sending", false, 3000);
      tryCompare(beeperData, "draftText", "", 3000);
      tryVerify(() => beeperData.messages.some(message => message.text === text), 3000);
      const sent = beeperData.messages.filter(message => message.text === text);
      compare(sent.length, 1);
      verify(sent[0].id.startsWith("demo-send-"), "The message ID must have been generated by Go.");
      compare(sent[0].chatID, chatID);
      verify(sent[0].isSender);
      compare(beeperData.messages.length, originalCount + 1);

      // HTTP-style response refresh and unsolicited Go events both load the page.
      // They must merge the same sent message without duplicating its bubble.
      beeperData.refresh();
      wait(350);
      tryCompare(beeperData, "loadingMessages", false, 3000);
      compare(beeperData.messages.filter(message => message.text === text).length, 1);
      compare(beeperData.messages.length, originalCount + 1);

      let cleared = false, clearedDraft = null;
      beeperData.request("getDraft", {chatID: chatID}, (result, error) => {
        clearedDraft = result; cleared = !error;
      });
      tryVerify(() => cleared, 3000);
      compare(clearedDraft.text, "");
    }

    function test_unknown_method_is_a_safe_error_and_transport_survives() {
      const originalCount = beeperData.chats.length;
      let completed = false, failure = null;
      beeperData.request("unknownProtocolTestMethod", {chatID: beeperData.currentChatID}, (result, error) => {
        failure = error; completed = true;
      });
      tryVerify(() => completed, 3000);
      verify(!!failure);
      compare(failure.code, "unknown_method");
      compare(failure.message, "Unknown command.");
      compare(beeperData.lastError, failure.message);
      verify(!failure.message.includes("Bearer") && !failure.message.includes("token"));
      compare(beeperData.chats.length, originalCount);

      let status = null;
      beeperData.request("status", {}, (result, error) => { if (!error) status = result; });
      tryVerify(() => status !== null, 3000);
      compare(status.state, "demo");
      verify(beeperData.connected);
    }
  }
}
