// Regenerate the offline QML catalogue from a pinned, integrity-checked release.
// Run from any directory: node desktop/ui/icons/update-lucide.mjs
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {writeFile} from 'node:fs/promises';

const version = '1.49.0';
const integrity = 'gSjtl7bR2v26oDInh2Wua1PrF2BRRXl9inhnLWcFfnRqRShmgZvlFRisPHqTfU7kxsuZU8ThNjAFotbInrzKow==';
const url = `https://registry.npmjs.org/lucide-static/-/lucide-static-${version}.tgz`;
const response = await fetch(url);
if (!response.ok) throw new Error(`Download failed: ${response.status}`);
const archive = Buffer.from(await response.arrayBuffer());
if (createHash('sha512').update(archive).digest('base64') !== integrity) throw new Error('Lucide integrity mismatch');
const read = file => execFileSync('tar', ['-xzOf', '-', `package/${file}`], {input: archive, encoding: 'utf8', maxBuffer: 16 * 1024 * 1024});
const nodes = JSON.parse(read('icon-nodes.json'));
const escape = value => String(value).replaceAll('&', '&amp;').replaceAll('"', '&quot;').replaceAll('<', '&lt;');
const icons = Object.fromEntries(Object.keys(nodes).sort().map(name => [name, nodes[name].map(([tag, attributes]) =>
  `<${tag} ${Object.entries(attributes).filter(([key]) => key !== 'key').map(([key, value]) => `${key}="${escape(value)}"`).join(' ')}/>`).join('')]));
await writeFile(new URL('LucideData.js', import.meta.url), `.pragma library\n// Generated by update-lucide.mjs; Lucide ${version}. See LICENSE.\nvar version = ${JSON.stringify(version)};\nvar icons = ${JSON.stringify(icons, null, 2)};\n`);
await writeFile(new URL('LICENSE', import.meta.url), read('LICENSE'));
console.log(`Generated ${Object.keys(icons).length} Lucide icons (${version}).`);
