// Regenerate the offline picker catalogue from pinned Unicode/CLDR releases.
// Prints a complete apply_patch document; it never edits the worktree itself.
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';

const sources = [
  'https://www.unicode.org/Public/17.0.0/emoji/emoji-test.txt',
  'https://raw.githubusercontent.com/unicode-org/cldr/release-48/common/annotations/fr.xml',
  'https://raw.githubusercontent.com/unicode-org/cldr/release-48/common/annotationsDerived/fr.xml',
  'https://www.unicode.org/license.txt'
];
const [emojiText, french, frenchDerived, license] = await Promise.all(sources.map(async url => {
  const response = await fetch(url, {signal: AbortSignal.timeout(30000)});
  if (!response.ok) throw new Error(`${response.status}: ${url}`);
  return response.text();
}));
if (!emojiText.includes('# Version: 17.0')) throw new Error('Unexpected emoji data version');
const decode = text => text.replace(/&(amp|lt|gt|quot|apos|#x[\da-f]+|#\d+);/gi, (_, entity) =>
  entity.startsWith('#x') ? String.fromCodePoint(parseInt(entity.slice(2), 16))
    : entity.startsWith('#') ? String.fromCodePoint(Number(entity.slice(1)))
      : ({amp: '&', lt: '<', gt: '>', quot: '"', apos: "'"})[entity]);
const canonical = text => text.replace(/\ufe0f/g, '');
const translations = new Map();
for (const xml of [french, frenchDerived]) {
  for (const match of xml.matchAll(/<annotation\s+([^>]+)>([^<]+)<\/annotation>/g)) {
    const cp = /\bcp="([^"]+)"/.exec(match[1]);
    if (!cp) continue;
    const key = canonical(decode(cp[1]));
    translations.set(key, ((translations.get(key) || '') + ' ' + decode(match[2])).trim());
  }
}
const entries = [];
for (const line of emojiText.split('\n')) {
  const match = /^([0-9A-F ]+)\s*;\s*fully-qualified\s*#\s*\S+\s+E[\d.]+\s+(.+)$/.exec(line);
  if (!match) continue;
  const emoji = String.fromCodePoint(...match[1].trim().split(/\s+/).map(code => parseInt(code, 16)));
  entries.push([emoji, match[2], translations.get(canonical(emoji)) || '']);
}
if (entries.length < 3000 || !translations.size) throw new Error('Incomplete emoji catalogue');
const output = `.pragma library

// Generated by generate-emojis.mjs. Unicode Emoji 17.0 and CLDR 48.
// The complete catalogue is local; opening/searching the picker uses no network.
/*
${sources.join('\n')}

${license.trim()}
*/
var rows = [
${entries.map(entry => '  ' + JSON.stringify(entry)).join(',\n')}
];
var indexed = null;
function normalize(value) {
  return String(value || "").normalize("NFD").replace(/[\\u0300-\\u036f]/g, "").toLowerCase().replace(/œ/g, "oe").replace(/æ/g, "ae");
}
function search(query) {
  if (!indexed) indexed = rows.map(row => ({emoji: row[0], name: row[1], keywords: normalize(row.join(" "))}));
  const words = normalize(query).trim().split(/\\s+/).filter(Boolean);
  return words.length ? indexed.filter(entry => words.every(word => entry.keywords.includes(word))) : indexed;
}
`;
const target = fileURLToPath(new URL('./BeeperEmojiData.js', import.meta.url));
const previous = await readFile(target, 'utf8').catch(error => {
  if (error.code === 'ENOENT') return null;
  throw error;
});
if (previous === output) {
  process.stderr.write('Emoji catalogue is already current.\n');
  process.exit(0);
}
const lines = (text, prefix) => text.trimEnd().split('\n').map(line => prefix + line).join('\n');
process.stdout.write('*** Begin Patch\n' + (previous === null
  ? '*** Add File: ' + target + '\n' + lines(output, '+')
  : '*** Update File: ' + target + '\n@@\n' + lines(previous, '-') + '\n' + lines(output, '+')) + '\n*** End Patch\n');
