import {test, expect} from '@playwright/test';
import path from 'node:path';

test('3D, controls, idle rendering and responsive layout', async ({page}) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => {
    if (message.type() === 'error') errors.push(message.text());
  });
  await page.goto('/');
  const canvas = page.locator('#scene');
  await expect(canvas).toHaveAttribute('data-ready', 'true');
  await expect(page.locator('#error')).toBeHidden();
  const outside = await page.request.get('/@fs/' + path.resolve('../../../flake.nix'));
  expect(outside.status()).toBe(403);
  await expect(canvas).toHaveAttribute('data-height-scale', '0.08');
  await expect(canvas).toHaveAttribute('data-join', 'cushion');
  await expect(page.locator('#provenance-info')).toContainText('Coussin validé');
  expect(Number(await canvas.getAttribute('data-vertices'))).toBeGreaterThan(20_000);
  await page.screenshot({path: 'test-results/viewer-default.png'});
  const peak = await canvas.getAttribute('data-peak');
  await page.getByRole('button', {name: 'Mat', exact: true}).click();
  await page.screenshot({path: 'test-results/viewer-cushion-matte.png'});
  await page.getByRole('button', {name: 'Galet précédent', exact: true}).click();
  await expect(canvas).toHaveAttribute('data-join', 'pebble');
  await expect(page.locator('#provenance-info')).toContainText('Galet précédent archivé');
  await expect(canvas).toHaveAttribute('data-peak', peak!);
  await page.screenshot({path: 'test-results/viewer-pebble-matte.png'});
  await page.locator('#join').selectOption('smooth');
  await expect(canvas).toHaveAttribute('data-join', 'smooth');
  await expect(page.locator('#provenance-info')).toContainText('Profil précédent archivé');
  await expect(canvas).toHaveAttribute('data-peak', peak!);
  await page.screenshot({path: 'test-results/viewer-previous-matte.png'});
  await page.getByRole('button', {name: 'Galet précédent'}).click();
  await expect(canvas).toHaveAttribute('data-join', 'pebble');
  await expect(page.locator('#join')).toHaveValue('pebble');

  await page.getByRole('button', {name: 'Profil', exact: true}).click();
  await page.getByLabel('Coupe centrale').check();
  await expect(canvas).toHaveAttribute('data-cut', 'true');
  await page.getByRole('button', {name: 'Mat', exact: true}).click();
  await expect(canvas).toHaveAttribute('data-material', 'matte');
  await page.locator('#join').selectOption('legacy');
  await expect(canvas).toHaveAttribute('data-join', 'legacy');
  await expect(page.locator('#join-note')).toContainText('brusquement');
  await page.locator('#join').selectOption('smooth');
  await page.getByRole('button', {name: 'Échelle verticale ×1'}).click();
  await expect(canvas).toHaveAttribute('data-height-scale', '1');
  await page.screenshot({path: 'test-results/viewer-profile-raw.png'});
  await page.getByRole('button', {name: 'Vue lisible ×0,08'}).click();
  await page.getByLabel('Coupe centrale').uncheck();
  await page.getByRole('button', {name: 'Capsule', exact: true}).click();
  await expect(page.locator('#width-value')).toHaveText('260 px');
  await expect(page.locator('#height-value')).toHaveText('36 px');
  await page.getByRole('button', {name: 'Calendrier', exact: true}).click();
  await expect(page.locator('#width-value')).toHaveText('434 px');
  await page.getByRole('button', {name: 'Lanceur', exact: true}).click();
  await page.getByRole('button', {name: 'Coussin · widgets', exact: true}).click();
  await expect(canvas).toHaveAttribute('data-join', 'cushion');
  await page.getByRole('button', {name: 'Tester des coins serrés · 2 px'}).click();
  await expect(page.locator('#radius-value')).toHaveText('2 px');
  await page.screenshot({path: 'test-results/viewer-cushion-small-radius.png'});
  await page.getByRole('button', {name: 'Galet précédent'}).click();
  await expect(canvas).toHaveAttribute('data-join', 'pebble');
  await expect(page.locator('#radius-value')).toHaveText('2 px');
  await page.getByRole('button', {name: 'Coussin · widgets'}).click();
  await expect(page.locator('#join')).toHaveValue('cushion');
  await page.getByRole('button', {name: 'Maillage', exact: true}).click();
  await expect(canvas).toHaveAttribute('data-material', 'wire');
  await page.getByLabel('Teinte de sélection').uncheck();
  await page.getByLabel('Largeur', {exact: true}).fill('600');
  await expect(page.locator('#width-value')).toHaveText('600 px');
  await page.getByRole('button', {name: 'Perspective', exact: true}).click();
  const box = (await canvas.boundingBox())!;
  const before = Number(await canvas.getAttribute('data-frames'));
  await page.mouse.move(box.x + box.width * 0.4, box.y + box.height * 0.4);
  await page.mouse.down();
  await page.mouse.move(box.x + box.width * 0.55, box.y + box.height * 0.5, {steps: 8});
  await page.mouse.up();
  await page.mouse.wheel(0, -150);
  await expect.poll(async () => Number(await canvas.getAttribute('data-frames'))).toBeGreaterThan(before);
  await page.waitForTimeout(2500);
  const idle = await canvas.getAttribute('data-frames');
  await page.waitForTimeout(500);
  expect(await canvas.getAttribute('data-frames')).toBe(idle);
  await page.setViewportSize({width: 390, height: 844});
  await expect(canvas).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(391);
  await page.screenshot({path: 'test-results/viewer-mobile.png', fullPage: true});
  expect(errors).toEqual([]);
});
